version: "3"

volumes:
  frontend-public-volume:

  hashbash-data:
    external: true

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - hashbash-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 55672:55672

  webpack_builder:
    image: jnorwood/hashbash-webpack_builder:current
    build:
      context: ..
      dockerfile: docker/Dockerfile-webpack_builder
    entrypoint:
      - node_modules/webpack/bin/webpack.js
      - --watch
      - --devtool
      - source-map
    volumes:
      - ../web/src:/var/lib/johnmalcolmnorwood/hashbash/src:ro
      - frontend-public-volume:/var/lib/johnmalcolmnorwood/hashbash/dist

  nginx:
    image: jnorwood/hashbash-nginx:current
    build:
      context: ..
      dockerfile: docker/Dockerfile-nginx
    entrypoint:
      - nginx
      - -c
      - /etc/nginx/local/nginx.conf
      - -g
      - daemon off;
    volumes:
      - ../etc/nginx:/etc/nginx/local:ro
      - frontend-public-volume:/var/lib/johnmalcolmnorwood/hashbash/dist:ro
    ports:
      - 80:80

  hashbash-webapp:
    image: jnorwood/hashbash-webapp:20.0104.0
    environment:
      - SPRING_PROFILES_ACTIVE=LCL,DCK,OVR

  hashbash-consumers:
    image: jnorwood/hashbash-consumers:20.0104.0
    environment:
      - SPRING_PROFILES_ACTIVE=LCL,DCK,OVR
