FROM node:8.11.1-slim
MAINTAINER John Norwood

WORKDIR /opt/hashbash
COPY package.json .
RUN npm install

COPY .babelrc .
COPY .eslintrc .
COPY webpack.config.js .

ENTRYPOINT ["node_modules/webpack/bin/webpack.js", "-p", "--progress"]
